/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.lanchonete.view;

import br.com.lanchonete.dao.BebidaDAO;
import br.com.lanchonete.dao.ClienteDAO;
import br.com.lanchonete.model.BebidaModel;
import br.com.lanchonete.model.ClienteModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ftana
 */
public class CadastrarBebidaView extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarBebidaView
     */
    public CadastrarBebidaView() {
        initComponents();
        listarBebidas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtFieldNomeBebida = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtFieldPrecoBebida = new javax.swing.JTextField();
        BtnCadastrarBebida = new javax.swing.JButton();
        BtnTelaPrincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbBebidas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        TxtFieldNomeBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNomeBebidaActionPerformed(evt);
            }
        });

        jLabel2.setText("Preço");

        TxtFieldPrecoBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldPrecoBebidaActionPerformed(evt);
            }
        });

        BtnCadastrarBebida.setText("Cadastrar Bebida");
        BtnCadastrarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarBebidaActionPerformed(evt);
            }
        });

        BtnTelaPrincipal.setText("Tela Principal");
        BtnTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTelaPrincipalActionPerformed(evt);
            }
        });

        TbBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço"
            }
        ));
        jScrollPane1.setViewportView(TbBebidas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFieldNomeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFieldPrecoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCadastrarBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(BtnTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFieldNomeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFieldPrecoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(BtnCadastrarBebida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnTelaPrincipal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFieldPrecoBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldPrecoBebidaActionPerformed
       this.dispose(); 
       TeleInicialView tiv = new TeleInicialView();
       tiv.setVisible(true);        }//GEN-LAST:event_TxtFieldPrecoBebidaActionPerformed

    private void BtnCadastrarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarBebidaActionPerformed
         String nome;
         double preco;
         
         nome = TxtFieldNomeBebida.getText();
         preco = Double.parseDouble(TxtFieldPrecoBebida.getText());
         
         BebidaModel bebida = new BebidaModel();
         
         bebida.setNome(nome);
         bebida.setPreco(preco);
         
         BebidaDAO bebidaDao = new BebidaDAO();
         bebidaDao.CadastrarBebida(bebida);       
         listarBebidas();
         
    }//GEN-LAST:event_BtnCadastrarBebidaActionPerformed

    private void BtnTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTelaPrincipalActionPerformed
       this.dispose();
       TeleInicialView tiv = new TeleInicialView();
       tiv.setVisible(true);        }//GEN-LAST:event_BtnTelaPrincipalActionPerformed

    private void TxtFieldNomeBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNomeBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNomeBebidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarBebidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarBebidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarBebidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarBebidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarBebidaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrarBebida;
    private javax.swing.JButton BtnTelaPrincipal;
    private javax.swing.JTable TbBebidas;
    private javax.swing.JTextField TxtFieldNomeBebida;
    private javax.swing.JTextField TxtFieldPrecoBebida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private void listarBebidas() {
    try {
            BebidaDAO bebidadao = new BebidaDAO();
            DefaultTableModel model = (DefaultTableModel) TbBebidas.getModel();
            model.setNumRows(0);
            ArrayList<BebidaModel> bebidas = bebidadao.MostrarBebidas();
            for (int num = 0; num < bebidas.size(); num++) {
                model.addRow(new Object[]{
                    bebidas.get(num).getNome(),
                    bebidas.get(num).getPreco()
                });

            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro para listar os clientes: " + erro);
        }
}
}
